# Generated by Django 5.2.1 on 2025-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("source_id", models.CharField(max_length=255, unique=True)),
                ("lover", models.IntegerField(blank=True, null=True)),
                ("imdb", models.FloatField(blank=True, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                ("genres", models.ManyToManyField(to="show_app.genre")),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="%(class)s_acted", to="show_app.person"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="%(class)s_directed", to="show_app.person"
                    ),
                ),
            ],
            options={
                "ordering": ["-release_year"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["release_year"], name="show_app_mo_release_b06500_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("source_id", models.CharField(max_length=255, unique=True)),
                ("lover", models.IntegerField(blank=True, null=True)),
                ("imdb", models.FloatField(blank=True, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="%(class)s_acted", to="show_app.person"
                    ),
                ),
                (
                    "directors",
                    models.ManyToManyField(
                        related_name="%(class)s_directed", to="show_app.person"
                    ),
                ),
                ("genres", models.ManyToManyField(to="show_app.genre")),
            ],
            options={
                "ordering": ["-release_year"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["release_year"], name="show_app_se_release_f71485_idx"
                    )
                ],
            },
        ),
    ]
